name: AWS DEPLOY
# turn off deploy to AWS

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.AWS_DB_HOST }}
      DB_PW: ${{ secrets.AWS_DB_PW}}
      DB_USER: ${{ secrets.AWS_DB_USER }}
      DB_NAME: ${{ secrets.AWS_DB_NAME }}
      SECRET_KEY: ${{secrets.AWS_SECRET_KEY }}
      COHERE_API_KEY: ${{secrets.RECOMMENDATIONS_API_KEY }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v1
      - run: npm install

      - run: |
          touch .env
          echo DB_HOST = "$AWS_DB_HOST" >> .env
          echo DB_PW = "$AWS_DB_PW" >> .env
          echo DB_USER = "$AWS_DB_USER" >> .env
          echo DB_NAME = "$AWS_DB_NAME" >> .env
          echo SECRET_KEY = "$AWS_SECRET_KEY" >> .env
          echo RECOMMENDATIONS_API_KEY = "$RECOMMENDATIONS_API_KEY" >> .env

      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deploy/"
          REMOTE_HOST: "ec2-13-218-196-80.compute-1.amazonaws.com"
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/book-tracker-backend"
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: "ubuntu@ec2-13-218-196-80.compute-1.amazonaws.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            cd nodeapps/book-tracker-backend
            npm install
            sudo systemctl stop book-tracker-backend
            sudo cp book-tracker-backend.service /lib/systemd/system/book-tracker-backend.service
            sudo systemctl daemon-reload
            sudo systemctl start book-tracker-backend
